"use server";

import { after } from "next/server";
import {
  getDb,
  restaurants,
  orders,
  orderItems,
  users,
  sql,
  restaurantProducts,
  eq,
  type CryptoAmount,
  outbox,
} from "@repo/database";
import { currentUser } from "@clerk/nextjs/server";
import {
  OutboxService,
  OutboxRelayService,
  isReplayAllowed,
  AppConfig,
} from "@repo/shared";
import { revalidatePath } from "next/cache";
import { randomUUID } from "crypto";
import {
  createPublicClient,
  http,
  type Hash,
  type Address,
  parseUnits,
  parseEther,
  formatUnits,
} from "viem";
import { base } from "viem/chains";
import {
  getCryptoPrices,
  usdToCryptoBigInt,
} from "@repo/shared/utils/crypto-price";
import {
  verifyTransaction,
  isValidTxHash,
  isValidAddress,
} from "@repo/shared/utils/web3-verification";

export interface Vendor {
  id: string;
  name: string;
  address: string | null;
  slug: string;
  category: string;
  rating: number;
  image: string;
  distance?: number;
}

export interface MenuItem {
  id: string;
  name: string;
  description: string | null;
  price: number;
  category: string;
}

export async function getRealVendors(
  userLat?: number,
  userLng?: number,
): Promise<Vendor[]> {
  try {
    if (!userLat || !userLng) {
      // Return empty list if no location provided (no fallback to SF)
      return [];
    }

    // 0.7 degrees is roughly 50 miles / 80 kilometers
    const RADIUS_LIMIT = 0.7;

    // Use PostgreSQL to calculate distance and sort by proximity
    // Distance = sqrt( (lat2-lat1)^2 + (lng2-lng1)^2 )
    // lat/lng are now numeric columns (precision 10, scale 7) - no casting needed
    const data = await getDb().execute(sql`
      SELECT id, name, address, slug, lat, lng,
        sqrt(
          pow(lat::double precision - ${userLat}::double precision, 2) +
          pow(lng::double precision - ${userLng}::double precision, 2)
        ) as distance
      FROM restaurants
      WHERE is_shadow = false
        AND is_claimed = true
        -- Filter out restaurants with invalid coordinates
        AND lat IS NOT NULL
        AND lng IS NOT NULL
        -- Hard radius limit: only show restaurants within ~50 miles
        AND lat::double precision BETWEEN ${userLat - RADIUS_LIMIT}::double precision AND ${userLat + RADIUS_LIMIT}::double precision
        AND lng::double precision BETWEEN ${userLng - RADIUS_LIMIT}::double precision AND ${userLng + RADIUS_LIMIT}::double precision
      ORDER BY distance ASC
      LIMIT 20
    `);

    return data.rows.map((r: any) => ({
      id: r.id,
      name: r.name,
      address: r.address || "Address unavailable",
      slug: r.slug,
      category: "Restaurant",
      rating: 4.5,
      image: "🍽️",
      distance: parseFloat(r.distance) || undefined,
    }));
  } catch (error) {
    console.error("Failed to fetch vendors:", error);
    throw new Error("Could not load restaurants");
  }
}

export async function getMenu(restaurantId: string): Promise<MenuItem[]> {
  try {
    const products = await getDb()
      .select()
      .from(restaurantProducts)
      .where(eq(restaurantProducts.restaurantId, restaurantId));

    return products.map((p: typeof restaurantProducts.$inferSelect) => ({
      id: p.id,
      name: p.name,
      description: p.description,
      price: p.price,
      category: p.category,
    }));
  } catch (error) {
    console.error("Failed to fetch menu:", error);
    throw new Error("Could not load menu items");
  }
}

/**
 * Get Restaurant Wallet Address
 *
 * Fetches the crypto wallet address for a restaurant to enable direct payments.
 */
export async function getRestaurantWallet(restaurantId: string): Promise<{
  success: boolean;
  walletAddress?: string | null;
  error?: string;
}> {
  try {
    const restaurant = await getDb().query.restaurants.findFirst({
      where: eq(restaurants.id, restaurantId),
      columns: {
        walletAddress: true,
      },
    });

    if (!restaurant) {
      return {
        success: false,
        error: "Restaurant not found",
      };
    }

    return {
      success: true,
      walletAddress: restaurant.walletAddress,
    };
  } catch (error) {
    console.error("Failed to fetch restaurant wallet:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Failed to fetch wallet",
    };
  }
}

/**
 * Place a real order with crypto payment verification
 *
 * ZERO-TRUST ARCHITECTURE:
 * - Frontend proposes transaction, backend MUST verify on-chain
 * - Transaction hash is verified before order is confirmed
 * - Payment must match expected amount and recipient
 *
 * @param clientOrderId - Order ID generated by the frontend and signed by the client.
 *   This ensures the EIP-712 signature binds to the correct orderId.
 *   Falls back to a new UUID for non-crypto orders.
 */
export async function placeRealOrder(
  vendorId: string,
  items: Array<{ id: string; name: string; price: number; quantity: number }>,
  deliveryAddress?: string,
  tipAmount: number = 0,
  // Web3 payment parameters
  paymentParams?: {
    txHash: string; // Transaction hash (will be verified on-chain)
    walletAddress: string; // User's wallet address
    paymentCurrency?: string; // Token symbol (USDC, ETH, etc.)
    chainId?: number; // Blockchain chain ID (default: Base)
    restaurantWalletAddress?: string; // Direct payment to restaurant wallet
    signature?: string; // Cryptographic signature of orderId (required for verification)
  },
  clientOrderId?: string, // Order ID generated client-side for signature binding
) {
  const user = await currentUser();

  if (!user) {
    throw new Error("You must be logged in to place an order.");
  }

  const restaurant = await getDb().query.restaurants.findFirst({
    where: sql`${restaurants.id} = ${vendorId}`,
  });

  if (!restaurant) {
    throw new Error("Restaurant not found");
  }

  // Use the client-provided ID (which the signature binds to) or fallback to new UUID
  const orderId = clientOrderId || randomUUID();

  // Validate clientOrderId format if provided to prevent ID spoofing
  if (
    clientOrderId &&
    !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(
      clientOrderId,
    )
  ) {
    throw new Error("Invalid order ID format");
  }

  // Convert fiat amounts to crypto smallest units (Wei for ETH, atomic for USDC)
  // CRITICAL: Use integer math (cents) from the start to avoid floating-point precision loss
  const paymentCurrency = paymentParams?.paymentCurrency || "USDC";
  const subtotalCents = items.reduce(
    (sum, item) => sum + Math.round(item.price * 100) * item.quantity,
    0,
  );
  const tipCents = Math.round(Math.max(0, tipAmount) * 100);
  const totalCents = subtotalCents + tipCents;

  let subtotalCrypto: string;
  let tipCrypto: string;
  let totalCrypto: string;

  if (paymentCurrency === "ETH") {
    // Use exact market rate - slippage is checked inside verifyTransaction
    subtotalCrypto = (
      await usdToCryptoBigInt(BigInt(subtotalCents), "ETH")
    ).toString();
    tipCrypto = (await usdToCryptoBigInt(BigInt(tipCents), "ETH")).toString();
    totalCrypto = (
      await usdToCryptoBigInt(BigInt(totalCents), "ETH")
    ).toString();
  } else {
    // USDC: 6 decimals, assume 1 USD = 1 USDC
    // 1 USD = 100 cents. 1 USDC = 1,000,000 atomic units.
    // Multiplier from cents to 6-decimal USDC is 10,000 (10^4).
    totalCrypto = (BigInt(totalCents) * 10000n).toString();
    subtotalCrypto = (BigInt(subtotalCents) * 10000n).toString();
    tipCrypto = (BigInt(tipCents) * 10000n).toString();
  }

  // ============================================================================
  // ZERO-TRUST: Verify on-chain transaction BEFORE inserting order
  // ============================================================================

  if (paymentParams?.txHash) {
    // Validate transaction hash format
    if (!isValidTxHash(paymentParams.txHash)) {
      throw new Error("Invalid transaction hash format");
    }

    // Validate wallet address format
    if (!isValidAddress(paymentParams.walletAddress)) {
      throw new Error("Invalid wallet address format");
    }

    // ============================================================================
    // REPLAY GUARD: Atomically register the txHash to prevent replay attacks
    // This is a TOCTOU-safe check that registers the transaction upfront.
    // If the order creation fails later, we rollback this registration.
    // ============================================================================
    const replayCheck = await isReplayAllowed({
      txHash: paymentParams.txHash as Hash,
      appSource: "open-delivery",
      entityId: orderId,
    });

    if (!replayCheck) {
      throw new Error(
        `Payment transaction ${paymentParams.txHash.substring(0, 10)}... was already used or blocked.`,
      );
    }

    // Verify transaction on-chain using shared utility
    const slippageBps =
      paymentCurrency === "ETH" ? AppConfig.getSlippageBps() : undefined;
    const verificationResult = await verifyTransaction({
      txHash: paymentParams.txHash as Hash,
      expectedValue: BigInt(totalCrypto),
      walletAddress: paymentParams.walletAddress as Address,
      chainId: paymentParams.chainId,
      expectedRecipient: paymentParams.restaurantWalletAddress as
        | Address
        | undefined,
      paymentCurrency,
      orderId, // Required for signature verification
      signature: paymentParams.signature as `0x${string}` | undefined,
      appSource: "open-delivery",
      slippageBps,
    });

    if (!verificationResult.success) {
      // COMPENSATING ACTION: Rollback the replay guard registration
      // so the user can retry with this valid txHash
      await rollbackReplayGuard(paymentParams.txHash as Hash);
      throw new Error(
        `Payment verification failed: ${verificationResult.error}`,
      );
    }

    console.log(`[Order ${orderId}] Payment verified on-chain:`, {
      txHash: paymentParams.txHash,
      confirmations: verificationResult.receipt?.confirmations,
      blockNumber: verificationResult.receipt?.blockNumber.toString(),
    });
  }

  try {
    // ========================================================================
    // CRITICAL FIX: Neon HTTP driver does NOT support interactive transactions
    // across multiple await ticks. We use a raw SQL CTE to atomically:
    //   1. Upsert the user (ON CONFLICT DO UPDATE)
    //   2. Insert the order (with duplicate payment hash check)
    //   3. Insert order items
    //   4. Write the outbox event
    // All within a single SQL statement, avoiding lock-drop issues.
    // ========================================================================

    const address = deliveryAddress;
    if (!address) {
      throw new Error(
        "No delivery address provided. A delivery address is required.",
      );
    }

    const itemsJson = JSON.stringify(items);
    const outboxEventJson = JSON.stringify({
      eventType: "WORKFLOW_STATE_CHANGED",
      payload: {
        executionId: orderId,
        timestamp: new Date().toISOString(),
        eventType: "delivery.intent_created",
        channel: "nervous-system:updates",
        data: {
          orderId: orderId,
          fulfillmentId: orderId,
          pickupAddress: address,
          deliveryAddress: address,
          price: totalCrypto,
          priority: "standard",
          items: items.map((item) => ({
            name: item.name,
            quantity: item.quantity,
            price: item.price,
          })),
          payment: {
            txHash: paymentParams?.txHash,
            currency: paymentCurrency,
            walletAddress: paymentParams?.walletAddress,
          },
        },
      },
    });

    const result = await getDb().execute(sql`
      WITH user_upsert AS (
        INSERT INTO ${users} (clerk_id, email, name, role)
        VALUES (
          ${user.id},
          ${user.emailAddresses[0].emailAddress},
          ${`${user.firstName || "User"} ${user.lastName || ""}`},
          'shopper'
        )
        ON CONFLICT (clerk_id) DO UPDATE SET
          email = EXCLUDED.email,
          name = EXCLUDED.name,
          updated_at = NOW()
        RETURNING *
        LIMIT 1
      ),
      order_insert AS (
        INSERT INTO ${orders} (
          id, user_id, store_id, status, subtotal, tip, total,
          delivery_address, pickup_address, payment_tx_hash,
          wallet_address, payment_currency, created_at, updated_at
        )
        SELECT
          ${orderId},
          u.id,
          ${vendorId},
          'pending_verification',
          ${subtotalCrypto}::numeric,
          ${tipCrypto}::numeric,
          ${totalCrypto}::numeric,
          ${address},
          ${restaurant.address || "Restaurant Location"},
          ${paymentParams?.txHash || null},
          ${paymentParams?.walletAddress || null},
          ${paymentCurrency},
          NOW(),
          NOW()
        FROM user_upsert u
        ${
          paymentParams?.txHash
            ? sql`WHERE NOT EXISTS (
                SELECT 1 FROM ${orders} o WHERE o.payment_tx_hash = ${paymentParams.txHash}
              )`
            : sql``
        }
        RETURNING *
      ),
      items_insert AS (
        INSERT INTO ${orderItems} (order_id, name, quantity, price, created_at)
        SELECT
          ${orderId},
          item->>'name',
          (item->>'quantity')::integer,
          (item->>'price')::numeric,
          NOW()
        FROM order_insert oi, jsonb_array_elements(${itemsJson}::jsonb) item
        RETURNING *
      ),
      outbox_insert AS (
        INSERT INTO ${outbox} (event_type, payload, created_at)
        SELECT
          'WORKFLOW_STATE_CHANGED',
          ${outboxEventJson}::jsonb,
          NOW()
        FROM order_insert
        RETURNING *
      )
      SELECT o.* FROM order_insert o
    `);

    if (!result || result.length === 0) {
      if (paymentParams?.txHash) {
        throw new Error(
          `Payment transaction ${paymentParams.txHash} already used for another order.`,
        );
      }
      throw new Error("Failed to create order.");
    }

    const newOrder = result[0];

    // Trigger the outbox relay AFTER the transaction commits.
    // Wrapped in after() to guarantee execution outside the request lifecycle.
    after(() => {
      OutboxRelayService.triggerRelay(orderId).catch((err) => {
        console.error(`[Order ${orderId}] Outbox relay trigger failed:`, err);
      });
    });

    revalidatePath("/customer");

    return {
      success: true,
      orderId: newOrder.id,
      status: "pending" as const,
      payment: {
        txHash: paymentParams?.txHash,
        currency: paymentCurrency,
        verified: !!paymentParams?.txHash,
      },
    };
  } catch (error) {
    // ========================================================================
    // CRITICAL FIX: If the DB fails AFTER on-chain payment was verified,
    // we MUST NOT rollback the replay guard. The funds are already captured
    // by the escrow contract. Instead, route to a DLQ for manual reconciliation.
    // ========================================================================
    if (paymentParams?.txHash) {
      console.error(
        `CRITICAL: Order creation failed but payment ${paymentParams.txHash} may have been captured. Routing to manual reconciliation.`,
        error,
      );
      // TODO: Push to Redis DLQ for admin reconciliation dashboard
    }

    console.error("Order placement failed:", error);
    throw new Error("Failed to place order. Please try again.");
  }
}
